# Generated by Django 3.0.7 on 2020-06-25 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.custome_dbtypes


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings', '0002_settings_init_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='CajasOperaciones',
            fields=[
                ('caja_operacion_id', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', utils.custome_dbtypes.DateFieldCustome(blank=True, null=True)),
                ('aperturado', models.CharField(max_length=10)),
                ('monto_apertura', models.DecimalField(decimal_places=2, max_digits=10)),
                ('usuario_apertura_id', models.IntegerField()),
                ('usuario_apertura_r_id', models.IntegerField()),
                ('cerrado', models.CharField(max_length=10)),
                ('monto_cierre', models.DecimalField(decimal_places=2, max_digits=10)),
                ('usuario_cierre_id', models.IntegerField()),
                ('usuario_cierre_r_id', models.IntegerField()),
                ('created_at', utils.custome_dbtypes.DateTimeFieldCustome(blank=True, null=True)),
                ('updated_at', utils.custome_dbtypes.DateTimeFieldCustome(blank=True, null=True)),
                ('deleted_at', utils.custome_dbtypes.DateTimeFieldCustome(blank=True, null=True)),
                ('caja_id', models.ForeignKey(db_column='caja_id', on_delete=django.db.models.deletion.PROTECT, to='settings.Cajas')),
                ('status_id', models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.PROTECT, to='status.Status')),
            ],
            options={
                'db_table': 'cajas_operaciones',
            },
        ),
        migrations.CreateModel(
            name='CajasOperacionesDetalles',
            fields=[
                ('caja_operacion_detalle_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cantidad_apertura', models.IntegerField()),
                ('cantidad_cierre', models.IntegerField()),
                ('caja_operacion_id', models.ForeignKey(db_column='caja_operacion_id', on_delete=django.db.models.deletion.PROTECT, to='cajas.CajasOperaciones')),
                ('moneda_id', models.ForeignKey(db_column='moneda_id', on_delete=django.db.models.deletion.PROTECT, to='monedas.Monedas')),
            ],
            options={
                'db_table': 'cajas_operaciones_detalles',
            },
        ),
        migrations.CreateModel(
            name='CajasIngresos',
            fields=[
                ('caja_ingreso_id', models.IntegerField(primary_key=True, serialize=False)),
                ('socio_cambio_estado_id', models.IntegerField(default=0)),
                ('socio_cobro_id', models.IntegerField(default=0)),
                ('fecha', utils.custome_dbtypes.DateTimeFieldCustome(blank=True, null=True)),
                ('concepto', models.CharField(max_length=250)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('user_id_anula', models.IntegerField(null=True)),
                ('motivio_anula', models.CharField(max_length=250, null=True)),
                ('created_at', utils.custome_dbtypes.DateTimeFieldCustome(blank=True, null=True)),
                ('updated_at', utils.custome_dbtypes.DateTimeFieldCustome(blank=True, null=True)),
                ('deleted_at', utils.custome_dbtypes.DateTimeFieldCustome(blank=True, null=True)),
                ('caja_id', models.ForeignKey(db_column='caja_id', on_delete=django.db.models.deletion.PROTECT, to='settings.Cajas')),
                ('punto_id', models.ForeignKey(db_column='punto_id', on_delete=django.db.models.deletion.PROTECT, to='settings.Puntos')),
                ('status_id', models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.PROTECT, to='status.Status')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cajas_ingresos',
            },
        ),
        migrations.CreateModel(
            name='CajasEgresos',
            fields=[
                ('caja_egreso_id', models.IntegerField(primary_key=True, serialize=False)),
                ('socio_cambio_estado_id', models.IntegerField(default=0)),
                ('socio_cobro_id', models.IntegerField(default=0)),
                ('fecha', utils.custome_dbtypes.DateTimeFieldCustome(blank=True, null=True)),
                ('concepto', models.CharField(max_length=250)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('user_id_anula', models.IntegerField(null=True)),
                ('motivio_anula', models.CharField(max_length=250, null=True)),
                ('created_at', utils.custome_dbtypes.DateTimeFieldCustome(blank=True, null=True)),
                ('updated_at', utils.custome_dbtypes.DateTimeFieldCustome(blank=True, null=True)),
                ('deleted_at', utils.custome_dbtypes.DateTimeFieldCustome(blank=True, null=True)),
                ('caja_id', models.ForeignKey(db_column='caja_id', on_delete=django.db.models.deletion.PROTECT, to='settings.Cajas')),
                ('punto_id', models.ForeignKey(db_column='punto_id', on_delete=django.db.models.deletion.PROTECT, to='settings.Puntos')),
                ('status_id', models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.PROTECT, to='status.Status')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cajas_egresos',
            },
        ),
    ]
