# Generated by Django 3.0.7 on 2020-06-14 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('status', '0002_status_init_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiposMonedas',
            fields=[
                ('tipo_moneda_id', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_moneda', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipos_monedas',
            },
        ),
        migrations.CreateModel(
            name='Monedas',
            fields=[
                ('moneda_id', models.IntegerField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status_id', models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.PROTECT, to='status.Status')),
                ('tipo_moneda_id', models.ForeignKey(db_column='tipo_moneda_id', on_delete=django.db.models.deletion.PROTECT, to='monedas.TiposMonedas')),
            ],
            options={
                'db_table': 'monedas',
            },
        ),
    ]
