# Generated by Django 3.0.7 on 2020-06-14 19:58

from django.db import migrations
from status.models import Status
from monedas.models import TiposMonedas, Monedas


def load_data(apps, schema_editor):
    status_activo = Status.objects.get(pk=1)

    # tipos de monedas
    tipo_moneda = TiposMonedas.objects.create(tipo_moneda_id=1, tipo_moneda='bolivianos', codigo='Bs.')
    tipo_moneda.save()
    tipo_moneda = TiposMonedas.objects.create(tipo_moneda_id=2, tipo_moneda='dolares', codigo='$us.')
    tipo_moneda.save()

    # tipo moneda bs
    tm_bs = TiposMonedas.objects.get(pk=1)

    # monedas bolivianos
    moneda = Monedas.objects.create(moneda_id=1, tipo_moneda_id=tm_bs, monto=0.10, status_id=status_activo)
    moneda.save()
    moneda = Monedas.objects.create(moneda_id=2, tipo_moneda_id=tm_bs, monto=0.20, status_id=status_activo)
    moneda.save()
    moneda = Monedas.objects.create(moneda_id=3, tipo_moneda_id=tm_bs, monto=0.50, status_id=status_activo)
    moneda.save()
    moneda = Monedas.objects.create(moneda_id=4, tipo_moneda_id=tm_bs, monto=1.00, status_id=status_activo)
    moneda.save()
    moneda = Monedas.objects.create(moneda_id=5, tipo_moneda_id=tm_bs, monto=2.00, status_id=status_activo)
    moneda.save()
    moneda = Monedas.objects.create(moneda_id=6, tipo_moneda_id=tm_bs, monto=5.00, status_id=status_activo)
    moneda.save()
    moneda = Monedas.objects.create(moneda_id=7, tipo_moneda_id=tm_bs, monto=10.00, status_id=status_activo)
    moneda.save()
    moneda = Monedas.objects.create(moneda_id=8, tipo_moneda_id=tm_bs, monto=20.00, status_id=status_activo)
    moneda.save()
    moneda = Monedas.objects.create(moneda_id=9, tipo_moneda_id=tm_bs, monto=50.00, status_id=status_activo)
    moneda.save()
    moneda = Monedas.objects.create(moneda_id=10, tipo_moneda_id=tm_bs, monto=100.00, status_id=status_activo)
    moneda.save()
    moneda = Monedas.objects.create(moneda_id=11, tipo_moneda_id=tm_bs, monto=200.00, status_id=status_activo)
    moneda.save()


def delete_data(apps, schema_editor):
    moneda = apps.get_model('monedas', 'Monedas')
    moneda.objects.all().delete

    tipos_monedas = apps.get_model('monedas', 'TiposMonedas')
    tipos_monedas.objects.all().delete


class Migration(migrations.Migration):

    dependencies = [
        ('monedas', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_data, delete_data)
    ]
