# Generated by Django 3.0.7 on 2020-06-25 21:52

from django.db import migrations, models
import django.db.models.deletion
import utils.custome_dbtypes


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cajas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CiExtensiones',
            fields=[
                ('ci_extension_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ci_extension', models.CharField(max_length=50)),
                ('orden', models.IntegerField()),
            ],
            options={
                'db_table': 'ci_extensiones',
            },
        ),
        migrations.CreateModel(
            name='Socios',
            fields=[
                ('socio_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ci_nit', models.CharField(max_length=50)),
                ('nombres', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=250)),
                ('telefonos', models.CharField(max_length=250)),
                ('numero_cuenta', models.IntegerField()),
                ('created_at', utils.custome_dbtypes.DateTimeFieldCustome(blank=True, null=True)),
                ('updated_at', utils.custome_dbtypes.DateTimeFieldCustome(blank=True, null=True)),
                ('deleted_at', utils.custome_dbtypes.DateTimeFieldCustome(blank=True, null=True)),
                ('ci_extension_id', models.ForeignKey(db_column='ci_extension_id', on_delete=django.db.models.deletion.PROTECT, to='socios.CiExtensiones')),
                ('status_id', models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.PROTECT, to='status.Status')),
                ('zona_id', models.ForeignKey(db_column='zona_id', on_delete=django.db.models.deletion.PROTECT, to='settings.Zonas')),
            ],
            options={
                'db_table': 'socios',
            },
        ),
        migrations.CreateModel(
            name='SociosCambiosEstados',
            fields=[
                ('socio_cambio_estado_id', models.IntegerField(primary_key=True, serialize=False)),
                ('status_id_1', models.IntegerField()),
                ('status_id_2', models.IntegerField()),
                ('motivo_cambio', models.CharField(max_length=250)),
                ('fecha_operacion', utils.custome_dbtypes.DateTimeFieldCustome(blank=True, null=True)),
                ('monto_bs', models.DecimalField(decimal_places=2, max_digits=10)),
                ('punto_id', models.IntegerField()),
                ('caja_id', models.IntegerField()),
                ('user_id_cobra', models.IntegerField()),
                ('created_at', utils.custome_dbtypes.DateTimeFieldCustome(blank=True, null=True)),
                ('updated_at', utils.custome_dbtypes.DateTimeFieldCustome(blank=True, null=True)),
                ('deleted_at', utils.custome_dbtypes.DateTimeFieldCustome(blank=True, null=True)),
                ('socio_id', models.ForeignKey(db_column='socio_id', on_delete=django.db.models.deletion.PROTECT, to='socios.Socios')),
                ('status_id', models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.PROTECT, to='status.Status')),
            ],
            options={
                'db_table': 'socios_cambios_estados',
            },
        ),
    ]
