# Generated by Django 3.0.7 on 2020-06-25 21:54

from django.db import migrations
from socios.models import CiExtensiones


def load_data(apps, schema_editor):
    ci = CiExtensiones.objects.create(ci_extension_id=1, ci_extension='cba', orden=1)
    ci.save()
    ci = CiExtensiones.objects.create(ci_extension_id=2, ci_extension='scz', orden=2)
    ci.save()
    ci = CiExtensiones.objects.create(ci_extension_id=3, ci_extension='lpz', orden=3)
    ci.save()
    ci = CiExtensiones.objects.create(ci_extension_id=4, ci_extension='scr', orden=4)
    ci.save()
    ci = CiExtensiones.objects.create(ci_extension_id=5, ci_extension='tr', orden=5)
    ci.save()
    ci = CiExtensiones.objects.create(ci_extension_id=6, ci_extension='be', orden=6)
    ci.save()
    ci = CiExtensiones.objects.create(ci_extension_id=7, ci_extension='pa', orden=7)
    ci.save()
    ci = CiExtensiones.objects.create(ci_extension_id=8, ci_extension='or', orden=8)
    ci.save()
    ci = CiExtensiones.objects.create(ci_extension_id=9, ci_extension='pt', orden=9)
    ci.save()


def delete_data(apps, schema_editor):
    ci = apps.get_model('socios', 'CiExtensiones')
    ci.objects.all().delete


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_data, delete_data),
    ]
