# Generated by Django 3.0.7 on 2020-06-15 19:05

from django.db import migrations
#from django.contrib.auth.models import User
from settings.models import Settings, Zonas, Puntos, CobrosManuales, CobrosMensuales, Cajas
from status.models import Status


def load_data(apps, schema_editor):
    #user_admin = User.objects.get(pk=2)
    status_activo = Status.objects.get(pk=1)

    setting = Settings.objects.create(setting_id=1, empresa='empresa', direccion='direccion', ciudad='ciudad', telefonos='telefonos', actividad='actividad', usar_fecha_servidor='si', fecha_sistema='now', cant_per_page=30,
                                      cantidad_lista=30, perfiles_admin_listado_cajas="'1','2'", costo_m3='1.00', costo_minimo='10.00', unidad_minima_m3='10.00', periodo_ini='202001', periodo_fin='202012', multa_pasivo='700.00', cant_lista_cobranza=10)
    setting.save()

    zona = Zonas.objects.create(zona_id=1, zona='zona 1', status_id=status_activo, created_at='now', updated_at='now')
    zona.save()

    cobro_manual = CobrosManuales.objects.create(cobro_manual_id=1, cobro_manual='multa retraso', monto_bs='5.00', status_id=status_activo, created_at='now', updated_at='now')
    cobro_manual.save()
    cobro_manual = CobrosManuales.objects.create(cobro_manual_id=2, cobro_manual='multa falta', monto_bs='20.00', status_id=status_activo, created_at='now', updated_at='now')
    cobro_manual.save()

    cobro_mensual = CobrosMensuales.objects.create(cobro_mensual_id=1, cobro_mensual='cuota mortorio', monto_bs='1.00', status_id=status_activo, created_at='now', updated_at='now')
    cobro_mensual.save()

    punto1 = Puntos.objects.create(punto_id=1, caja_id=1, punto='Punto 1', codigo='P1', impresora_reportes='', status_id=status_activo, created_at='now', updated_at='now')
    punto1.save()

    punto1 = Puntos.objects.get(pk=1)
    caja1 = Cajas.objects.create(caja_id=1, punto_id=punto1, caja='caja1', codigo='C1', status_id=status_activo, created_at='now', updated_at='now')
    caja1.save()


def delete_data(apps, schema_editor):
    caja = apps.get_model('settings', 'Cajas')
    caja.objects.all().delete

    punto = apps.get_model('settings', 'Puntos')
    punto.objects.all().delete

    cobro_mensual = apps.get_model('settings', 'CobrosMensuales')
    cobro_mensual.objects.all().delete

    cobro_manual = apps.get_model('settings', 'CobrosManuales')
    cobro_manual.objects.all().delete

    zona = apps.get_model('settings', 'Zonas')
    zona.objects.all().delete

    setting = apps.get_model('settings', 'Settings')
    setting.objects.all().delete


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_data, delete_data)
    ]
