# Generated by Django 3.0.7 on 2020-06-25 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tablas_backup', '0002_tablas_backup_init_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='TmpListadoMes',
            fields=[
                ('tmp_listado_mes_id', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.CharField(max_length=50)),
                ('operacion', models.CharField(max_length=250)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mes', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tmp_listado_mes',
            },
        ),
    ]
