# Generated by Django 3.0.7 on 2020-06-11 21:00

from django.db import migrations
from status.models import Status


def load_data(apps, schema_editor):
    status_add = Status.objects.create(status_id=1, status='activo')
    status_add.save()
    status_add = Status.objects.create(status_id=2, status='inactivo')
    status_add.save()
    status_add = Status.objects.create(status_id=3, status='dliminado')
    status_add.save()
    status_add = Status.objects.create(status_id=4, status='apertura')
    status_add.save()
    status_add = Status.objects.create(status_id=5, status='apertura_recibe')
    status_add.save()
    status_add = Status.objects.create(status_id=6, status='cierre')
    status_add.save()
    status_add = Status.objects.create(status_id=7, status='cierre_recibe')
    status_add.save()
    status_add = Status.objects.create(status_id=8, status='anulado')
    status_add.save()
    status_add = Status.objects.create(status_id=9, status='pasivo')
    status_add.save()
    status_add = Status.objects.create(status_id=10, status='cobrado')
    status_add.save()
    status_add = Status.objects.create(status_id=11, status='no_aperturado')
    status_add.save()


def delete_data(apps, schema_editor):
    status = apps.get_model('status', 'Status')
    status.objects.all().delete


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_data, delete_data),
    ]
