# Generated by Django 3.0.7 on 2020-06-25 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lecturas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablasBackup',
            fields=[
                ('tabla', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('posicion', models.IntegerField()),
            ],
            options={
                'db_table': 'tablas_backup',
            },
        ),
    ]
