# Generated by Django 3.0.7 on 2020-06-25 22:37

from django.db import migrations
from tablas_backup.models import TablasBackup


def load_data(apps, schema_editor):
    tb = TablasBackup.objects.create(tabla='perfiles', posicion=1)
    tb.save()
    tb = TablasBackup.objects.create(tabla='puntos', posicion=2)
    tb.save()
    tb = TablasBackup.objects.create(tabla='tipos_monedas', posicion=3)
    tb.save()
    tb = TablasBackup.objects.create(tabla='monedas', posicion=4)
    tb.save()
    tb = TablasBackup.objects.create(tabla='status', posicion=5)
    tb.save()
    tb = TablasBackup.objects.create(tabla='tmp_listado_mes', posicion=6)
    tb.save()
    tb = TablasBackup.objects.create(tabla='zonas', posicion=7)
    tb.save()
    tb = TablasBackup.objects.create(tabla='modulos', posicion=8)
    tb.save()
    tb = TablasBackup.objects.create(tabla='settings', posicion=9)
    tb.save()
    tb = TablasBackup.objects.create(tabla='users', posicion=9)
    tb.save()
    tb = TablasBackup.objects.create(tabla='users_modulos', posicion=10)
    tb.save()
    tb = TablasBackup.objects.create(tabla='ci_extensiones', posicion=11)
    tb.save()
    tb = TablasBackup.objects.create(tabla='puntos_configuraciones', posicion=12)
    tb.save()
    tb = TablasBackup.objects.create(tabla='cobros_manuales', posicion=13)
    tb.save()
    tb = TablasBackup.objects.create(tabla='cobros_mensuales', posicion=14)
    tb.save()
    tb = TablasBackup.objects.create(tabla='cajas', posicion=15)
    tb.save()
    tb = TablasBackup.objects.create(tabla='cajas_egresos', posicion=16)
    tb.save()
    tb = TablasBackup.objects.create(tabla='cajas_ingresos', posicion=17)
    tb.save()
    tb = TablasBackup.objects.create(tabla='cajas_operaciones', posicion=18)
    tb.save()
    tb = TablasBackup.objects.create(tabla='cajas_operaciones_d', posicion=19)
    tb.save()
    tb = TablasBackup.objects.create(tabla='socios', posicion=20)
    tb.save()
    tb = TablasBackup.objects.create(tabla='socios_cambios_estado', posicion=21)
    tb.save()
    tb = TablasBackup.objects.create(tabla='lecturas', posicion=22)
    tb.save()
    tb = TablasBackup.objects.create(tabla='socios_cobros', posicion=23)
    tb.save()
    tb = TablasBackup.objects.create(tabla='socios_cobros_detalles', posicion=24)
    tb.save()
    tb = TablasBackup.objects.create(tabla='socios_cobros_manuales', posicion=25)
    tb.save()
    tb = TablasBackup.objects.create(tabla='socios_cobros_mensuales', posicion=26)
    tb.save()
    tb = TablasBackup.objects.create(tabla='lecturas_anulados', posicion=27)
    tb.save()
    tb = TablasBackup.objects.create(tabla='socios_cobros_anulados', posicion=28)
    tb.save()
    tb = TablasBackup.objects.create(tabla='socios_cobros_detalles_anulados', posicion=29)
    tb.save()
    tb = TablasBackup.objects.create(tabla='socios_cobros_manuales_anulados', posicion=30)
    tb.save()
    tb = TablasBackup.objects.create(tabla='socios_cobros_mensuales_anulados', posicion=31)
    tb.save()


def delete_data(apps, schema_editor):
    tb = apps.get_model('tablas_backup', 'TablasBackup')
    tb.objects.all().delete


class Migration(migrations.Migration):

    dependencies = [
        ('tablas_backup', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_data, delete_data),
    ]
