# Generated by Django 3.0.7 on 2020-06-12 14:38
from django.contrib.auth.models import User
from django.db import migrations
from permisos.models import Modulos, UsersModulos


def load_data(apps, schema_editor):
    # grupo 1, cobranza
    modulo_insert = Modulos.objects.create(modulo_id=1, modulo='cobranza', modulo_txt='Cobranza', enabled=True, position=1, grupo=1)
    modulo_insert.save()

    modulo_insert = Modulos.objects.create(modulo_id=2, modulo='lecturas', modulo_txt='Lecturas', enabled=True, position=2, grupo=1)
    modulo_insert.save()

    modulo_insert = Modulos.objects.create(modulo_id=3, modulo='asignar_cobros_manuales', modulo_txt='Asignar Cobros Manuales', enabled=True, position=3, grupo=1)
    modulo_insert.save()

    modulo_insert = Modulos.objects.create(modulo_id=4, modulo='socios', modulo_txt='Socios', enabled=True, position=2, grupo=1)
    modulo_insert.save()

    # grupo2, operaciones caja
    modulo_insert = Modulos.objects.create(modulo_id=5, modulo='iniciar_caja', modulo_txt='Inicar Caja', enabled=True, position=1, grupo=2)
    modulo_insert.save()

    modulo_insert = Modulos.objects.create(modulo_id=6, modulo='iniciar_caja_recibir', modulo_txt='Aceptar Inicio Caja', enabled=True, position=2, grupo=2)
    modulo_insert.save()

    modulo_insert = Modulos.objects.create(modulo_id=7, modulo='entregar_caja', modulo_txt='Entregar Caja', enabled=True, position=3, grupo=2)
    modulo_insert.save()

    modulo_insert = Modulos.objects.create(modulo_id=8, modulo='entregar_caja_recibir', modulo_txt='Aceptar Entrega Caja', enabled=True, position=4, grupo=2)
    modulo_insert.save()

    modulo_insert = Modulos.objects.create(modulo_id=9, modulo='cajas_ingresos', modulo_txt='Ingresos Caja', enabled=True, position=5, grupo=2)
    modulo_insert.save()

    modulo_insert = Modulos.objects.create(modulo_id=10, modulo='cajas_egresos', modulo_txt='Egresos Caja', enabled=True, position=6, grupo=2)
    modulo_insert.save()

    # grupo 3, configuraciones
    modulo_insert = Modulos.objects.create(modulo_id=11, modulo='usuarios', modulo_txt='Usuarios', enabled=True, position=1, grupo=3)
    modulo_insert.save()

    modulo_insert = Modulos.objects.create(modulo_id=12, modulo='cobros_manuales', modulo_txt='Cobros Manuales', enabled=True, position=2, grupo=3)
    modulo_insert.save()

    modulo_insert = Modulos.objects.create(modulo_id=13, modulo='cobros_mensuales', modulo_txt='Cobros Mensuales', enabled=True, position=3, grupo=3)
    modulo_insert.save()

    modulo_insert = Modulos.objects.create(modulo_id=14, modulo='zonas', modulo_txt='Zonas', enabled=True, position=4, grupo=3)
    modulo_insert.save()

    modulo_insert = Modulos.objects.create(modulo_id=15, modulo='configuraciones_sistema', modulo_txt='Configuraciones Sistema', enabled=True, position=5, grupo=3)
    modulo_insert.save()

    # grupo 4, herramientas
    modulo_insert = Modulos.objects.create(modulo_id=16, modulo='corregir_lectura', modulo_txt='Corregir Lectura', enabled=True, position=1, grupo=4)
    modulo_insert.save()
    modulo_insert = Modulos.objects.create(modulo_id=17, modulo='tablas_backup', modulo_txt='Backup', enabled=True, position=2, grupo=4)
    modulo_insert.save()

    # grupo 5, reportes
    modulo_insert = Modulos.objects.create(modulo_id=18, modulo='reportes', modulo_txt='Reportes', enabled=True, position=1, grupo=5)
    modulo_insert.save()

    # para el usuarios por defecto
    user2 = User.objects.get(pk=2)
    modulo1 = Modulos.objects.get(pk=1)
    modulo2 = Modulos.objects.get(pk=2)
    modulo3 = Modulos.objects.get(pk=3)
    modulo4 = Modulos.objects.get(pk=4)
    modulo5 = Modulos.objects.get(pk=5)
    modulo6 = Modulos.objects.get(pk=6)
    modulo7 = Modulos.objects.get(pk=7)
    modulo8 = Modulos.objects.get(pk=8)
    modulo9 = Modulos.objects.get(pk=9)
    modulo10 = Modulos.objects.get(pk=10)
    modulo11 = Modulos.objects.get(pk=11)
    modulo12 = Modulos.objects.get(pk=12)
    modulo13 = Modulos.objects.get(pk=13)
    modulo14 = Modulos.objects.get(pk=14)
    modulo15 = Modulos.objects.get(pk=15)
    modulo16 = Modulos.objects.get(pk=16)
    modulo17 = Modulos.objects.get(pk=17)
    modulo18 = Modulos.objects.get(pk=18)

    user_modulo = UsersModulos.objects.create(user_modulo_id=1, user_id=user2, modulo_id=modulo1, enabled=True,
                                              adicionar=True, modificar=True, eliminar=True, anular=True, imprimir=True, permiso=True)
    user_modulo.save()

    user_modulo = UsersModulos.objects.create(user_modulo_id=2, user_id=user2, modulo_id=modulo2, enabled=True,
                                              adicionar=True, modificar=True, eliminar=True, anular=True, imprimir=True, permiso=True)
    user_modulo.save()

    user_modulo = UsersModulos.objects.create(user_modulo_id=3, user_id=user2, modulo_id=modulo3, enabled=True,
                                              adicionar=True, modificar=True, eliminar=True, anular=True, imprimir=True, permiso=True)
    user_modulo.save()
    user_modulo = UsersModulos.objects.create(user_modulo_id=4, user_id=user2, modulo_id=modulo4, enabled=True,
                                              adicionar=True, modificar=True, eliminar=True, anular=True, imprimir=True, permiso=True)
    user_modulo.save()
    user_modulo = UsersModulos.objects.create(user_modulo_id=5, user_id=user2, modulo_id=modulo5, enabled=True,
                                              adicionar=True, modificar=True, eliminar=True, anular=True, imprimir=True, permiso=True)
    user_modulo.save()
    user_modulo = UsersModulos.objects.create(user_modulo_id=6, user_id=user2, modulo_id=modulo6, enabled=True,
                                              adicionar=True, modificar=True, eliminar=True, anular=True, imprimir=True, permiso=True)
    user_modulo.save()
    user_modulo = UsersModulos.objects.create(user_modulo_id=7, user_id=user2, modulo_id=modulo7, enabled=True,
                                              adicionar=True, modificar=True, eliminar=True, anular=True, imprimir=True, permiso=True)
    user_modulo.save()
    user_modulo = UsersModulos.objects.create(user_modulo_id=8, user_id=user2, modulo_id=modulo8, enabled=True,
                                              adicionar=True, modificar=True, eliminar=True, anular=True, imprimir=True, permiso=True)
    user_modulo.save()
    user_modulo = UsersModulos.objects.create(user_modulo_id=9, user_id=user2, modulo_id=modulo9, enabled=True,
                                              adicionar=True, modificar=True, eliminar=True, anular=True, imprimir=True, permiso=True)
    user_modulo.save()
    user_modulo = UsersModulos.objects.create(user_modulo_id=10, user_id=user2, modulo_id=modulo10, enabled=True,
                                              adicionar=True, modificar=True, eliminar=True, anular=True, imprimir=True, permiso=True)
    user_modulo.save()
    user_modulo = UsersModulos.objects.create(user_modulo_id=11, user_id=user2, modulo_id=modulo11, enabled=True,
                                              adicionar=True, modificar=True, eliminar=True, anular=True, imprimir=True, permiso=True)
    user_modulo.save()
    user_modulo = UsersModulos.objects.create(user_modulo_id=12, user_id=user2, modulo_id=modulo12, enabled=True,
                                              adicionar=True, modificar=True, eliminar=True, anular=True, imprimir=True, permiso=True)
    user_modulo.save()
    user_modulo = UsersModulos.objects.create(user_modulo_id=13, user_id=user2, modulo_id=modulo13, enabled=True,
                                              adicionar=True, modificar=True, eliminar=True, anular=True, imprimir=True, permiso=True)
    user_modulo.save()
    user_modulo = UsersModulos.objects.create(user_modulo_id=14, user_id=user2, modulo_id=modulo14, enabled=True,
                                              adicionar=True, modificar=True, eliminar=True, anular=True, imprimir=True, permiso=True)
    user_modulo.save()
    user_modulo = UsersModulos.objects.create(user_modulo_id=15, user_id=user2, modulo_id=modulo15, enabled=True,
                                              adicionar=True, modificar=True, eliminar=True, anular=True, imprimir=True, permiso=True)
    user_modulo.save()
    user_modulo = UsersModulos.objects.create(user_modulo_id=16, user_id=user2, modulo_id=modulo16, enabled=True,
                                              adicionar=True, modificar=True, eliminar=True, anular=True, imprimir=True, permiso=True)
    user_modulo.save()
    user_modulo = UsersModulos.objects.create(user_modulo_id=17, user_id=user2, modulo_id=modulo17, enabled=True,
                                              adicionar=True, modificar=True, eliminar=True, anular=True, imprimir=True, permiso=True)
    user_modulo.save()
    user_modulo = UsersModulos.objects.create(user_modulo_id=18, user_id=user2, modulo_id=modulo18, enabled=True,
                                              adicionar=True, modificar=True, eliminar=True, anular=True, imprimir=True, permiso=True)
    user_modulo.save()


def delete_data(apps, schema_editor):
    user_modulo = apps.get_model('permisos', 'UsersModulos')
    user_modulo.objects.all().delete

    modulo = apps.get_model('permisos', 'Modulos')
    modulo.objects.all().delete


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_data, delete_data),
    ]
